"""
Load CAS/name pairs for substances present in the committed REACH demo zip.

The manifest ``data/reach_demo/reach_subset_examples.json`` is generated by
``scripts/refresh_reach_subset_examples.py`` (run after changing ``reach_subset.zip``).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

# Repo root = parent of utils/
_REPO_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_MANIFEST = _REPO_ROOT / "data" / "reach_demo" / "reach_subset_examples.json"


def reach_demo_examples_manifest_path() -> Path:
    return Path(os.environ.get("REACH_DEMO_EXAMPLES_JSON", "") or _DEFAULT_MANIFEST).expanduser()


def load_reach_demo_example_chemicals(*, max_n: int = 6) -> list[tuple[str, str]]:
    """
    Return up to ``max_n`` ``(cas, button_label)`` tuples for the main-page demo row.

    Empty list if the manifest is missing or invalid.
    """
    path = reach_demo_examples_manifest_path()
    if not path.is_file():
        return []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    if not isinstance(raw, list):
        return []
    out: list[tuple[str, str]] = []
    seen: set[str] = set()
    for item in raw:
        if len(out) >= max_n:
            break
        if not isinstance(item, dict):
            continue
        cas = str(item.get("cas") or "").strip()
        if not cas or cas in seen:
            continue
        seen.add(cas)
        name = str(item.get("name") or "").strip()
        short = name[:42] + "…" if len(name) > 42 else name
        label = f"{cas} ({short})" if short else f"{cas} (REACH demo)"
        out.append((cas, label))
    return out
